POST http://localhost:8000/products HTTP/1.0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjUxMTQxMjEsInN1YiI6ImFiMGFhMDk5LWUwYjEtNDY0Zi1hMWNiLTQ3NjI0NDE0NjQ4OCJ9.TbrFZImEEwn6rZpVj2Yg4OhyAkaOOGU5HkCY99oQVnE

{
    "name": "My Product",
    "price": 100
}

###
GET http://localhost:8000/products/bb052c8f-2079-42c4-a9cf-87d2f94c7104 HTTP/1.0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjUxNDAxMDAsInN1YiI6ImFiMGFhMDk5LWUwYjEtNDY0Zi1hMWNiLTQ3NjI0NDE0NjQ4OCJ9.HE5bvyV8tcUykL3Gvi8vlQTm85MQxf1G7PWaZ1SGV3w

###
PUT http://localhost:8000/products/f648fda8-d116-43bf-a304-9c5a29a5f14e HTTP/1.0
Content-Type: application/json

{
    "name": "Edit Product",
    "price": 200
}
