POST http://localhost:8000/products HTTP/1.0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjUwMTgyNTgsInN1YiI6ImVkYzA2ZGMyLWNjMmQtNDlmYi1hOTJiLTZkMGZmMWY1ZjU0YiJ9.zBswOVFmQaXR8IXI33X7BwA6ddJ8wpSAep_O9yz-Qlo

{
    "name": "My Product",
    "price": 100
}

###
GET http://localhost:8000/products/f648fda8-d116-43bf-a304-9c5a29a5f14e HTTP/1.0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjUwMTgyNTgsInN1YiI6ImVkYzA2ZGMyLWNjMmQtNDlmYi1hOTJiLTZkMGZmMWY1ZjU0YiJ9.zBswOVFmQaXR8IXI33X7BwA6ddJ8wpSAep_O9yz-Qlo

###
PUT http://localhost:8000/products/f648fda8-d116-43bf-a304-9c5a29a5f14e HTTP/1.0
Content-Type: application/json

{
    "name": "Edit Product",
    "price": 200
}
