version: "3"

services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    platform: linux/amd64
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: finance
    ports:
      - "5432:5432"
